### ISSUE TITLE
Future Roadmap

### ISSUE THREAD

**Issue by airbreather** [airbreather/StepperUpper#2]
Here are things I'd like to eventually get done sometime down the road.  They're just high-level ideas at this point.
- [ ] Support things like STEP Packs.  These would probably look like auxiliary XML files that assume that a particular set of setup tasks has already been run and not materially altered by the user in any way.  _While STEP Packs are the main use case for this, another use case would be to set system- or user-specific parameters like ENB's MEMORY / WINDOW config or other Skyrim INI tweaks like bGamepadEnable.  I keep finding myself adding / swapping a few lines here and there in the XML file when I run it for myself, so there's definitely **something** there._
- [ ] Allow the user to limit concurrency.
- [ ] Improve the user experience when there are "manual-only" files that need to be downloaded.
- [ ] Make certain things more generic so this could be used for other games, such as Fallout 4 or Skyrim: Special Edition.
- [ ] Optimize plugin cleaning performance.
- [ ] Interleave file checking with task running (perhaps optionally) so that we can, say, start with the plugin cleaning as soon as we detect the existence of each plugin file instead of waiting for unrelated files.
- [ ] Revive something like the "cached MD5" behavior to speed up "updates".
- [ ] Perhaps slightly optimize file checking by favoring files whose names match the "canonical name", before bothering to check other files with the same length.
- [ ] Improve my own experience when it comes to maintaining the XML file when people update their stuff.  This is particularly important when considering those projects that delete / hide old versions of their files when new versions are released.
- [ ] Generate ModOrganizer meta.ini files in the mod folders.
- [ ] Provide the ability to extract BSA files so they can be manipulated.

**Comment by airbreather** [comment]
Each entry is now its own individual work item.
